### ISSUE TITLE
Scrape of Forwards of Forwards failed

### ISSUE THREAD

**Issue by breviloquencestewardesses** [jordanwildon/Telepathy#10]
Hello, 

I want to report another issue. 

First, I scraped all forwards from a channel. That worked flawlessly. There were some expectations, but that was displayed transparently. Then, I tried to scrape all forwards from that forwards. For a while, it worked. At some point, this occured: 

`Traceback (most recent call last):
  File "telepathy.py", line 39, in <module>
    exec(open("archiver.py").read())
  File "<string>", line 164, in <module>
  File "<string>", line 48, in <module>
  File "<string>", line 166, in <module>
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "<string>", line 114, in new_main
  File "/home/osint/.local/lib/python3.8/site-packages/telethon/requestiter.py", line 58, in __anext__
    if await self._init(**self.kwargs):
  File "/home/osint/.local/lib/python3.8/site-packages/telethon/client/messages.py", line 26, in _init
    self.entity = await self.client.get_input_entity(entity)
  File "/home/osint/.local/lib/python3.8/site-packages/telethon/client/users.py", line 432, in get_input_entity
    await self._get_entity_from_string(peer))
  File "/home/osint/.local/lib/python3.8/site-packages/telethon/client/users.py", line 569, in _get_entity_from_string
    raise ValueError(
ValueError: Cannot find any entity corresponding to "Alternative History 2039"
`

After that, the scrape stopped. In the generated net.csv are all channels wich were scraped to this point. 

Is there a solution?

Thanks in advance,

Best wishes!

**Comment by breviloquencestewardesses** [comment]
Updated Telethon, rerun script, issue occured at the same point.

**Comment by jordanwildon** [comment]
Hey there. I'm working on fixing this and have found a potential solution. Just need to streamline it a bit and then I'll push it out!

**Comment by jordanwildon** [comment]
This issue should be resolved in an upcoming major update. Closing the issue now, but will reassess should something similar come up again.
