### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by Salavat-lab** [jordanwildon/Telepathy#11]
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/Telepathy/telepathy.py", line 45, in <module>
    exec(open("members.py").read())
  File "<string>", line 32, in <module>
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/telethon/sync.py", line 39, in syncified
    return loop.run_until_complete(coro)
  File "/data/data/com.termux/files/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/telethon/client/auth.py", line 368, in sign_in
    result = await self(request)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/telethon/client/users.py", line 79, in _call
    result = await future
telethon.errors.rpcbaseerrors.AuthKeyError: RPCError 406: UPDATE_APP_TO_LOGIN (caused by SignInRequest)
Segmentation fault

Please advise how to correct this error

**Comment by rmdes** [comment]
Wait, how did you solved this ?

**Comment by benborges** [comment]
I think this is solved by adding your phone number with 00 instead of + before your country indicator

**Comment by jordanwildon** [comment]
This appears to be an error due to Telegram updates and not Telepathy itself. Trying to work out how to squash this bug but can't seem to replicate it. Have updated everything with the release of 2.1.10 so it shouldn't persist.
