### ISSUE TITLE
Configuration error

### ISSUE THREAD

**Issue by osinter456** [jordanwildon/Telepathy#13]
hi i use pipe install and error at the config ->
 Enter code: 68842
Traceback (most recent call last):
  File "/home/XX/.local/bin/telepathy", line 8, in <module>
    sys.exit(cli())
  File "/home/XX.local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/XX/.local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/XX.local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/XX/.local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/XX/.local/lib/python3.8/site-packages/telepathy/telepathy.py", line 167, in cli
    client.sign_in(code=input(' Enter code: '))
  File "/usr/local/lib/python3.8/dist-packages/telethon/sync.py", line 39, in syncified
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/dist-packages/telethon/client/auth.py", line 368, in sign_in
    result = await self(request)
  File "/usr/local/lib/python3.8/dist-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/usr/local/lib/python3.8/dist-packages/telethon/client/users.py", line 79, in _call
    result = await future
telethon.errors.rpcbaseerrors.AuthKeyError: RPCError 406: UPDATE_APP_TO_LOGIN (caused by SignInRequest)

**Comment by benborges** [comment]
Have you configured it before attempting to run the code ?
you're having an error to authentify your account against telegram API, this is not a Telepathy issue.
