### ISSUE TITLE
 charmap' codec can't encode character 

### ISSUE THREAD

**Issue by pouling** [jordanwildon/Telepathy#15]
Hi, when I try to run telepathy.py -t <channel name> the scrip start and run, he create a csv that contain the header and information about my user (and sometime 2 or 3 more users) but crash right after

Windows 2016 latest patch with Python 3.10.5 with all package up to date
Any idea ?
-----
Traceback (most recent call last):
  File "D:\xxxxxx\telepathy.py", line 933, in <module>
    cli()
  File "D:\Users\noname\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "D:\Users\noname\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "D:\Users\noname\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\Users\noname\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "D:\xxxxxxxx\telepathy.py", line 930, in cli
    client.loop.run_until_complete(main())
  File "D:\Users\noname\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "D:\xxxxxxxx\telepathy.py", line 347, in main
    members_df.to_csv(save_members, sep=';')
  File "D:\Users\noname\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\generic.py", line 3551, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "D:\Users\noname\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\io\formats\format.py", line 1180, in to_csv
    csv_formatter.save()
  File "D:\Users\noname\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\io\formats\csvs.py", line 261, in save
    self._save()
  File "D:\Users\noname\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\io\formats\csvs.py", line 266, in _save
    self._save_body()
  File "D:\Users\noname\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\io\formats\csvs.py", line 304, in _save_body
    self._save_chunk(start_i, end_i)
  File "D:\Users\noname\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\io\formats\csvs.py", line 315, in _save_chunk
    libwriters.write_csv_rows(
  File "pandas\_libs\writers.pyx", line 55, in pandas._libs.writers.write_csv_rows
  File "D:\Users\noname\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001fa84' in position 22: character maps to <undefined>

**Comment by jordanwildon** [comment]
This seems to have been an issue with me not specifying the encoding. I’ve now changed this and will push it out in the next update.
