### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode character '\u2794' in position 108: character maps to <undefined>

### ISSUE THREAD

**Issue by pouling** [jordanwildon/Telepathy#20]
Script run for 8 hours until it crash at then end and the files was empty

D:\telepathy\dump\Telepathy\telepathy>telepathy -t MacacosCC -c

      ______     __                 __  __
     /_  __/__  / /__  ____  ____ _/ /_/ /_  __  __
      / / / _ \/ / _ \/ __ \/ __ `/ __/ __ \/ / / /
     / / /  __/ /  __/ /_/ / /_/ / /_/ / / / /_/ /
    /_/  \___/_/\___/ .___/\__,_/\__/_/ /_/\__, /
                   /_/                    /____/
    -- An OSINT toolkit for investigating Telegram chats.
    -- Developed by @jordanwildon | Version 2.0.0.

 [!] Performing comprehensive scan

 [-] Fetching details for MacacosCC...
  ┬  Chat details
  ├  Title: MacacoCC [OFC]
  ├  Description: FREE DBQuality before quantity 😎❤️Owner @VAL4K
  ├  Total participants: 7502
  ├  Username: MacacosCC
  ├  URL: http://t.me/MacacosCC
  ├  Chat type: Channel
  ├  Chat id: 1421996100
  ├  Access hash: xxxxxxxxxxxxxxxxxxx
  ├  Scam: False
  ├  First post date: 2021/05/31, 12:32 UTC
  └  Restrictions: None

 [!] Calculating number of messages...
 [-] Fetching message archive...
on 25900: Security error while unpacking a received message: Server replied with a wrong session ID
on 25900: Security error while unpacking a received message: Server replied with a wrong session ID
on 25900: Security error while unpacking a received message: Server replied with a wrong session ID
on 25900: Security error while unpacking a received message: Server replied with a wrong session ID
on 25900: Security error while unpacking a received message: Server replied with a wrong session ID
on 25900: Security error while unpacking a received message: Server replied with a wrong session ID
....... thousand of line later .......
 [-] Progress:  |████████████████████✗︎ (!) 169275/169262 [100%] in 8:57:36.3 (5.25/s)
Traceback (most recent call last):
  File "D:\Users\xxxxxxxxxxx\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Users\xxxxxxxxxxx\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\Users\xxxxxxxxxxx\AppData\Local\Programs\Python\Python310\Scripts\telepathy.exe\__main__.py", line 7, in <module>
  File "D:\Users\xxxxxxxxxxx\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "D:\Users\xxxxxxxxxxx\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "D:\Users\xxxxxxxxxxx\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\Users\xxxxxxxxxxx\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "D:\Users\xxxxxxxxxxx\AppData\Local\Programs\Python\Python310\lib\site-packages\telepathy\telepathy.py", line 930, in cli
    client.loop.run_until_complete(main())
  File "D:\Users\xxxxxxxxxxx\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "D:\Users\xxxxxxxxxxx\AppData\Local\Programs\Python\Python310\lib\site-packages\telepathy\telepathy.py", line 761, in main
    c_archive.to_csv(archive_file, sep=';')
  File "D:\Users\xxxxxxxxxxx\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\generic.py", line 3551, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "D:\Users\xxxxxxxxxxx\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\io\formats\format.py", line 1180, in to_csv
    csv_formatter.save()
  File "D:\Users\xxxxxxxxxxx\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\io\formats\csvs.py", line 261, in save
    self._save()
  File "D:\Users\xxxxxxxxxxx\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\io\formats\csvs.py", line 266, in _save
    self._save_body()
  File "D:\Users\xxxxxxxxxxx\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\io\formats\csvs.py", line 304, in _save_body
    self._save_chunk(start_i, end_i)
  File "D:\Users\xxxxxxxxxxx\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\io\formats\csvs.py", line 315, in _save_chunk
    libwriters.write_csv_rows(
  File "pandas\_libs\writers.pyx", line 55, in pandas._libs.writers.write_csv_rows
  File "D:\Users\xxxxxxxxxxx\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2794' in position 108: character maps to <undefined>

**Comment by jordanwildon** [comment]
Closed due to duplicate issue.
