### ISSUE TITLE
Help required

### ISSUE THREAD

**Issue by OsintUK** [jordanwildon/Telepathy#30]
Hi,

Can you help me please.

So I provide the following:
APP api id
APP api Hash
Mobile number
and then the mobile token.

I then provided the following test command: telepathy -t durov 

I then received the following: The API access for bot users is restricted. The method you tried cannot be executed as a bot (caused by GetHistoryRequest)

any advice would be grateful

**Comment by rotivrotiv** [comment]
Traceback (most recent call last):
  File "/home/kali/.local/bin/telepathy", line 8, in <module>
    sys.exit(cli())
  File "/home/kali/.local/lib/python3.10/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/kali/.local/lib/python3.10/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/kali/.local/lib/python3.10/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/kali/.local/lib/python3.10/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/kali/.local/lib/python3.10/site-packages/telepathy/telepathy.py", line 1740, in cli
    client.loop.run_until_complete(main())
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/kali/.local/lib/python3.10/site-packages/telepathy/telepathy.py", line 1658, in main
    result = await client(
  File "/home/kali/.local/lib/python3.10/site-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/home/kali/.local/lib/python3.10/site-packages/telethon/client/users.py", line 84, in _call
    result = await future
telethon.errors.rpcerrorlist.UserpicUploadRequiredError: You must have a profile picture before using this method (caused by GetLocatedRequest)

**Comment by jordanwildon** [comment]
> telethon.errors.rpcerrorlist.UserpicUploadRequiredError: You must have a profile picture before using this method (caused by GetLocatedRequest)

Referring you to the README:

"Finds users near to specified coordinates. Input should be longitude followed by latitude, seperated by a comma. **This feature only works if your Telegram account has a profile image which is set to be publicly viewable.**"

This is also made clear in the error message.

**Comment by jordanwildon** [comment]
> Hi,
> 
> Can you help me please.
> 
> So I provide the following: APP api id APP api Hash Mobile number and then the mobile token.
> 
> I then provided the following test command: telepathy -t durov
> 
> I then received the following: The API access for bot users is restricted. The method you tried cannot be executed as a bot (caused by GetHistoryRequest)
> 
> any advice would be grateful

Hello! Appears that you're using a bot API token and not a TDLib API key.

**Comment by OsintUK** [comment]
Thank you, you're correct, I need to wake up haha, cheers dude
