### ISSUE TITLE
AttributeError: 'User' object has no attribute 'title'

### ISSUE THREAD

**Issue by elabdi** [jordanwildon/Telepathy#32]
telepathy -t ***** -c

          ______     __                 __  __
         /_  __/__  / /__  ____  ____ _/ /_/ /_  __  __
          / / / _ \/ / _ \/ __ \/ __ `/ __/ __ \/ / / /
         / / /  __/ /  __/ /_/ / /_/ / /_/ / / / /_/ /
        /_/  \___/_/\___/ .___/\__,_/\__/_/ /_/\__, /
                       /_/                    /____/
        -- An OSINT toolkit for investigating Telegram chats.
        -- Developed by @jordanwildon | Version 2.2.62.

 [!] Performing comprehensive scan
 [-] Fetching details for Timifaithus...
Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python310\Scripts\telepathy.exe\__main__.py", line 7, in <module>
  File "C:\Python310\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Python310\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Python310\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Python310\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Python310\lib\site-packages\telepathy\telepathy.py", line 1759, in cli
    client.loop.run_until_complete(main())
  File "C:\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Python310\lib\site-packages\telepathy\telepathy.py", line 407, in main
    name = entity.title
AttributeError: 'User' object has no attribute 'title'

**Comment by aaarghhh** [comment]
Hi, I think that you are trying to use the flag -c on a user. 
The flag -c is a full scan for channel and groups.

PS: you missed to redact your target in the log. ^^

**Comment by elabdi** [comment]
> Hi, I think that you are trying to use the flag -c on a user. The flag -c is a full scan for channel and groups.
> 
> PS: you missed to redact your target in the log. ^^

hey mate, first thank you so much for your reply and trying to help, i will try it again and see if i will have any success.
best regards

PS : REDACTED THE TARGET :)

**Comment by elabdi** [comment]
i just tested it out and still gives the same error
