### ISSUE TITLE
Edgelist generate error

### ISSUE THREAD

**Issue by pouling** [jordanwildon/Telepathy#34]
Latest Telepathy version, latest Ubuntu patches
When I run the command, it work, but at the end it generate some error, the file edgelist.csv is created but I don't know if other files need to be created (node.csv). Also the user list is not created inside the folder
xxxxxx:~$ telepathy -t goutertropical -f

          ______     __                 __  __
         /_  __/__  / /__  ____  ____ _/ /_/ /_  __  __
          / / / _ \/ / _ \/ __ \/ __ `/ __/ __ \/ / / /
         / / /  __/ /  __/ /_/ / /_/ / /_/ / / / /_/ /
        /_/  \___/_/\___/ .___/\__,_/\__/_/ /_/\__, /
                       /_/                    /____/
        -- An OSINT toolkit for investigating Telegram chats.
        -- Developed by @jordanwildon | Version 2.3.2.
        
 [!] Performing basic scan
 [!] Forwards will be fetched
 [-] Fetching details for goutertropical...
  ┬  Chat details
  ├  Title: GRIOT
  ├  Description: "DU PORC"
  ├  Translated Description: N/A
  ├  Total participants: 416
  ├  Username: goutertropical
  ├  URL: http://t.me/goutertropical
  ├  Chat type: Channel
  ├  Chat id: 1426272611
  ├  Access hash: -1181623613396063021
  ├  Scam: False
  ├  First post date: 2022-10-30T14:55:52+00:00
  └  Restrictions: None
 [-] Calculating number of forwarded messages...
 [-] Fetching forwarded messages...
 [-] Progress:  |██████████████████▍⚠︎| (!) 22/24 [92%] in 13.4s (1.64/s
 [+] Forward scrape complete
  ┬  Statistics
Traceback (most recent call last):
  File "/home/xxx/.local/bin/telepathy", line 8, in <module>
    sys.exit(cli())
  File "/home/xxx/.local/lib/python3.10/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/xxx/.local/lib/python3.10/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/xxx/.local/lib/python3.10/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/xxx/.local/lib/python3.10/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/xxx/.local/lib/python3.10/site-packages/telepathy/telepathy.py", line 1740, in cli
    client.loop.run_until_complete(main())
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/xxx/.local/lib/python3.10/site-packages/telepathy/telepathy.py", line 784, in main
    print_shell("forwarder_stat",report_forward)
  File "/home/xxx/.local/lib/python3.10/site-packages/telepathy/utils.py", line 325, in print_shell
    "  ├  Forwarded messages found: ", str(obj.forward_count)
AttributeError: 'Object' object has no attribute 'forward_count'. Did you mean: 'forward_four'?

**Comment by jordanwildon** [comment]
This should now be fixed!

Good point regarding the node file. With Gephi, you shouldn't need this if the edgelist file is imported correctly, but I can look to ensuring Telepathy automatically creates it.

Feel free to reopen this issue if the problem persists.

**Comment by pouling** [comment]
Update code with pip3 install telepathy --upgrade
run telepathy -t goutertropical -f
same error
try to importe csv in gephy in edge or node tab
got these error for each line


Issue{message=[Record #27] Could not parse weight 'PhoneLineChannel', level=SEVERE}	SEVERE	
Issue{message=[Record #27] Could not parse weight 'goutertropical', level=SEVERE}	SEVERE	
Issue{message=[Record #27] Could not parse weight 'GRIOT', level=SEVERE}	SEVERE	
Issue{message=[Record #27] Could not parse weight 'PeerChannel(channel_id=1899862571)', level=SEVERE}	SEVERE	
Issue{message=[Record #27] Could not parse weight 'PhoneLineChannel', level=SEVERE}	SEVERE	
Issue{message=[Record #27] Could not parse weight '2022-11-02T14:26:05+00:00', level=SEVERE}	SEVERE	
Issue{message=[Record #28] Could not parse weight 'FEFE $HOP', level=SEVERE}	SEVERE	
Issue{message=[Record #28] Could not parse weight 'goutertropical', level=SEVERE}	SEVERE	
Issue{message=[Record #28] Could not parse weight 'GRIOT', level=SEVERE}	SEVERE	
Issue{message=[Record #28] Could not parse weight 'PeerChannel(channel_id=1613176949)', level=SEVERE}	SEVERE	
Issue{message=[Record #28] Could not parse weight '2022-11-02T14:11:03+00:00', level=SEVERE}	SEVERE	
Issue{message=[Record #28] Inconsistent number of matrix lines compared to the number of labels. 27 lines, 6 labels, level=WARNING}	WARNING

**Comment by cmelone** [comment]
@proseltd this issue has reappeared for me (version 2.3.2)

```
 [-] Progress:  |███████████████████▉⚠︎ (!) 957/961 [100%] in 11:03.9 (1.44/s)
 [+] Forward scrape complete
  ┬  Statistics
Traceback (most recent call last):
  File "/Users/user/.pyenv/versions/3.9.4/bin/telepathy", line 8, in <module>
    sys.exit(cli())
  File "/Users/user/.pyenv/versions/3.9.4/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/user/.pyenv/versions/3.9.4/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/user/.pyenv/versions/3.9.4/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/user/.pyenv/versions/3.9.4/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/user/.pyenv/versions/3.9.4/lib/python3.9/site-packages/telepathy/telepathy.py", line 1740, in cli
    client.loop.run_until_complete(main())
  File "/Users/user/.pyenv/versions/3.9.4/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/user/.pyenv/versions/3.9.4/lib/python3.9/site-packages/telepathy/telepathy.py", line 784, in main
    print_shell("forwarder_stat",report_forward)
  File "/Users/user/.pyenv/versions/3.9.4/lib/python3.9/site-packages/telepathy/utils.py", line 325, in print_shell
    "  ├  Forwarded messages found: ", str(obj.forward_count)
AttributeError: 'Object' object has no attribute 'forward_count'
```
