### ISSUE TITLE
Feature request - target Group Chat ID

### ISSUE THREAD

**Issue by jevgen** [jordanwildon/Telepathy#37]
I tried unsuccessfully targeting group chat ID. 
Currently script works for channels, but not for groups it seem. 
Is it possible to add support to archive and analyse Group Chats?

**Comment by aaarghhh** [comment]
Just tested, 
I can confirm that it works using "name_id" not the numeric one "(-100)xxxxxxxx" without the @. 

Can you try to analyze a public chat using it's "nickname" `xxxxxxxx`, or a private using the related link, like `https://t.me/joinchat/xxxxxxxxxxx` .

The usage is:
```
telepathy.py -t xxxxxxxx -c
```
where xxxxxxxx is the name of the chat.

**Comment by jevgen** [comment]
> Just tested, I can confirm that it works using "name_id" not the numeric one "(-100)xxxxxxxx" without the @.
> 
> Can you try to analyze a public chat using it's "nickname" `xxxxxxxx`, or a private using the related link, like `https://t.me/joinchat/xxxxxxxxxxx` .
> 
> The usage is:
> 
> ```
> telepathy.py -t xxxxxxxx -c
> ```
> 
> where xxxxxxxx is the name of the chat.

This is not how I can use it. On attempt to run from prompt I'm getting:

'Traceback (most recent call last):
  File "/opt/homebrew/bin/telepathy", line 8, in <module>
    sys.exit(cli())
  File "/opt/homebrew/lib/python3.10/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/homebrew/lib/python3.10/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/homebrew/lib/python3.10/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/telepathy/telepathy.py", line 1740, in cli
    client.loop.run_until_complete(main())
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/homebrew/lib/python3.10/site-packages/telepathy/telepathy.py", line 444, in main
    entity = await client.get_entity(t)
  File "/opt/homebrew/lib/python3.10/site-packages/telethon/client/users.py", line 335, in get_entity
    result.append(await self._get_entity_from_string(x))
  File "/opt/homebrew/lib/python3.10/site-packages/telethon/client/users.py", line 574, in _get_entity_from_string
    raise ValueError(
ValueError: Cannot find any entity corresponding to "-1756425942"'

and on attempt on running from full path I get:

'my@computer ~ % which telepathy.py
telepathy.py not found
my@computer ~ % locate telepathy.py
/opt/homebrew/lib/python3.10/site-packages/telepathy/telepathy.py
my@computer  ~ % /opt/homebrew/lib/python3.10/site-packages/telepathy/telepathy.py -t -1756425942 -c
zsh: permission denied: /opt/homebrew/lib/python3.10/site-packages/telepathy/telepathy.py
'

**Comment by jevgen** [comment]
Great news! Thank you so much.
