### ISSUE TITLE
Love the tool, more love available once it works for me :)

### ISSUE THREAD

**Issue by vredchenko** [jordanwildon/Telepathy#4]
Followed readme instructions to the latter, Telepathy dir chmoded to `755`,

```bash
python3 --version
Python 3.9.7
pip --version
pip 22.0.3 from /home/vredchenko/.local/lib/python3.9/site-packages/pip (python 3.9)
uname -a
Linux asus-tuf 5.15.23-76051523-generic #202202110435~1644952300~21.10~96763f1 SMP Tue Feb 15 19:52:40 U x86_64 x86_64 x86_64 GNU/Linux
``` 

I'd debug myself but right now lacking the time due to a tight deadline. Happy to provide more details / run more tests if it helps.

```
python3 telepathy.py 
Welcome to Telepathy
Please select a function:
1. Batch chat archiver
2. Archive within a timeframe
3. Scrape group members
4. Scrape forwarded messages in a chat
5. Lookup a user ID

Pick a number:1
Loading Batch chat archiver ...
Launching batch chat archiver
Welcome to the Telepathy archiving tool. This tool will archive Telegram chats based on a list.
Do you want to print messages to terminal while Telepathy runs? (y/n)y
Do you want to archive media content? (y/n)n
Archiving chats...
Traceback (most recent call last):
  File "/home/vredchenko/dev/donetcheng/Telepathy/telepathy.py", line 40, in <module>
    exec(open("archiver.py").read())
  File "<string>", line 150, in <module>
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "<string>", line 60, in main
  File "/home/vredchenko/.local/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/vredchenko/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/vredchenko/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/vredchenko/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/vredchenko/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/vredchenko/.local/lib/python3.9/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/vredchenko/.local/lib/python3.9/site-packages/pandas/io/parsers/base_parser.py", line 222, in _open_handles
    self.handles = get_handle(
  File "/home/vredchenko/.local/lib/python3.9/site-packages/pandas/io/common.py", line 702, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'to_archive.csv'
```

**Comment by vredchenko** [comment]
Possibly related to: https://github.com/jordanwildon/Telepathy/issues/1

**Comment by vredchenko** [comment]
Ah I found my problem: didn't pay attention enough to create the `to_archive.csv` file first. Closing issue
