### ISSUE TITLE
Error using archive.py

### ISSUE THREAD

**Issue by andre-santos1** [jordanwildon/Telepathy#6]
I ran archive.py and got the following error:

Traceback (most recent call last):
  File "/home/kali/Telepathy/archiver.py", line 31, in <module>
    client.sign_in(phone, input('Enter the code: '))
  File "/usr/local/lib/python3.9/dist-packages/telethon/sync.py", line 39, in syncified
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/dist-packages/telethon/client/auth.py", line 368, in sign_in
    result = await self(request)
  File "/usr/local/lib/python3.9/dist-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/usr/local/lib/python3.9/dist-packages/telethon/client/users.py", line 79, in _call
    result = await future
telethon.errors.rpcerrorlist.SessionPasswordNeededError: Two-steps verification is enabled and a password is required (caused by SignInRequest)

What am I doing wrong?

**Comment by jordanwildon** [comment]
Hey there! It looks like you have 2FA enabled on your account and I haven't put something into the authorization request to be able to properly allow for this. I'll work on a solution to this!
