### ISSUE TITLE
TypeError: 'ChannelParticipants' object is not subscriptable

### ISSUE THREAD

**Issue by Codeforhelping** [jordanwildon/Telepathy#8]
Traceback (most recent call last):
  File "C:\Users\visha\PycharmProjects\test\pythonProject2\Other Work\Error Fixing 6.py", line 65, in <module>
    all_participants = client.get_participants(target_group)
  File "C:\Paython 39\lib\site-packages\telethon\sync.py", line 39, in syncified
    return loop.run_until_complete(coro)
  File "C:\Paython 39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Paython 39\lib\site-packages\telethon\client\chats.py", line 507, in get_participants
    return await self.iter_participants(*args, **kwargs).collect()
  File "C:\Paython 39\lib\site-packages\telethon\requestiter.py", line 113, in collect
    async for message in self:
  File "C:\Paython 39\lib\site-packages\telethon\requestiter.py", line 74, in __anext__
    if await self._load_next_chunk():
  File "C:\Paython 39\lib\site-packages\telethon\client\chats.py", line 224, in _load_next_chunk
    participants = results[i]
TypeError: 'ChannelParticipants' object is not subscriptable

**Comment by jordanwildon** [comment]
Fix for this will soon be released in a major update,.
